// query RelatedTable, V — the BYSTANDER. Untouched, so it is never code-generated by the
// delta; it is only ever RESOLVED from the packaged baseline, where its dataitem records the
// source table by name.
query 72176 "BN Query Host"
{
    QueryType = Normal;
    Caption = 'BN Query Host';

    elements
    {
        dataitem(Data; "BN Query Table")
        {
            column(QueryNo; "No.") { }
            column(QueryDescription; Description) { }
        }
    }
}
